// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwwvcdpomohlvfxauaku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3d3ZjZHBvbW9obHZmeGF1YWt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MjI5MDgsImV4cCI6MjA2ODQ5ODkwOH0.MAo_632dgXb2T3BMdk7b39y0BXJCTwsR9Lt0rQM9XVc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});